[settings]
python.uv_venv_auto = true

[tools]
bun = "1.2.21"
uv = "0.8.16"
ruff = "0.12.10"
biome = "latest"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv --project datasets sync"

[tasks.dev]
description = "Run development server"
alias = "d"
run = "uv run marimo edit datasets/src/main.py"

[tasks.export]
description = "Export deps to requirements.txt"
run = "uv export --format requirements-txt --no-hashes --no-header --no-dev --no-annotate --output-file datasets/requirements.txt"

[tasks.fix]
description = "Lint & format (fix by default)"
alias = "f"
run = [
  "uv run ruff format . --config datasets/pyproject.toml",
  "uv run ruff check --fix --unsafe-fixes . --config pyproject.toml",
]
