[settings]
python.uv_venv_auto = true

[tools]
bun = "1.2.21"
uv = "0.8.16"
ruff = "0.12.10"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv sync --all-groups"

[tasks.export]
description = "Export deps to requirements.txt"
run = "uv export --format requirements-txt --no-hashes --no-header --no-dev --no-annotate --output-file requirements.txt"

[tasks.fix]
description = "Lint & format (fix by default)"
alias = "f"
run = [
  "uv run ruff format . --config pyproject.toml",
  "uv run ruff check --fix --unsafe-fixes . --config pyproject.toml",
]
