[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "marimo>=0.15.2",
    "matplotlib>=3.10.6",
    "polars>=1.33.1",
]
