[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "geopandas>=1.1.1",
    "marimo>=0.15.3",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
    "plotly[express]>=6.3.0",
    "polars>=1.33.1",
]
