export const marketingTheme = {
  navLinks: [
    { href: '/blog', label: 'Blog' },
    { href: '/#projects', label: 'Proyectos' },
    { href: '/#about', label: 'Nosotros' },
  ],
  layout: {
    headerMaxWidth: '1024px',
    contentMaxWidth: '624px',
    navMaxWidth: '1024px',
    navHeight: '64px',
  },
  spacing: {
    pageTop: 'pt-36',
    pageBottom: 'pb-32',
    pageSide: 'px-6',
    breadcrumbBottom: 'mb-3',
    thumbnailBottom: 'my-12',
    metaBottom: 'mb-19',
    navGap: 'gap-8',
  },
  nav: {
    logo: {
      fontSize: 'text-[16px]',
      fontWeight: 'font-semibold',
      textColor: 'text-gray-900',
      hoverColor: 'hover:text-gray-700',
      iconSize: 20,
    },
    links: {
      fontSize: 'text-[13px]',
      textColor: 'text-gray-600',
      hoverColor: 'hover:text-gray-900',
    },
    auth: {
      fontSize: 'text-[13px]',
      loginTextColor: 'text-gray-600',
      loginHoverColor: 'hover:text-gray-900',
      buttonGap: 'gap-5',
    },
    bar: {
      borderColor: 'border-gray-200',
      bgColor: 'bg-white/80',
      backdropBlur: 'backdrop-blur-sm',
    },
  },
  breadcrumb: {
    fontSize: 'text-[13px]',
    textColor: 'text-gray-500 font-medium',
    hoverColor: 'hover:text-gray-900',
    activeColor: 'text-gray-700',
    gap: 'gap-2',
  },
  title: {
    fontSize: 'text-[46px] md:text-[46px]',
    fontWeight: 'font-semibold',
    lineHeight: 'leading-[1.15]',
    tracking: 'tracking-tighter',
    textColor: 'text-gray-900',
    align: 'text-center mx-auto',
    maxWidth: 'max-w-4xl',
  },
  meta: {
    fontSize: 'text-[15px]',
    textColor: 'text-gray-500',
    align: 'justify-center',
    gap: 'gap-2',
    separator: '·',
  },
  thumbnail: {
    aspectRatio: 'aspect-[2.22/1]',
    bgColor: 'bg-[#1a1f2e]',
    borderRadius: 'rounded-2xl',
    placeholderTextColor: 'text-gray-500',
    placeholderTextSize: 'text-sm',
  },
  content: {
    fontSize: 'text-[17px]',
    lineHeight: 'leading-[1.7]',
    paragraphSpacing: 'mb-5',
    headingColor: 'text-gray-900',
    textColor: 'text-gray-700',
    linkColor: 'text-gray-900',
    linkDecoration: 'underline decoration-gray-400',
    linkHoverDecoration: 'hover:decoration-gray-900',
    codeInlineBg: 'bg-gray-100',
    codeInlineBorder: 'border-gray-200',
    codeInlineText: 'text-gray-800',
    codeBlockBg: 'bg-[#1a1a1a]',
    codeBlockBorder: 'border-gray-200',
    blockquoteBorder: 'border-gray-300',
    blockquoteText: 'text-gray-600',
  },
  transitions: {
    default: 'transition-colors',
    duration: 'duration-200',
  },
  colors: {
    background: '#fafaf9',
    text: 'text-gray-900',
  },
} as const;
